# SGLang bench serving启动配置
base_config:
  base_url: "http://127.0.0.1:8000"
  params:
    test_01:
      dataset-name: random
      max-concurrency: [ 1, 2, 4, 8, 10, 16, 32, 64, 80, 128 ]
      num-prompts: [ 320 ]
      random-input-output-len: [[ 10240, 256 ]]
    test_02:
      dataset-name: random
      max-concurrency: [ 1, 2, 4, 8, 10 ]
      num-prompts: [ 100 ]
      random-input-output-len: [[ 194560, 1024 ]]
    test_03:
      dataset-name: random
      max-concurrency: [ 32, 64 ]
      num-prompts: [ 1000 ]
      random-input-output-len: [[ 90000, 2000 ]]
    test_04:
      dataset-name: random
      max-concurrency: [ 1, 2, 4, 8, 16, 32, 64, 80, 128 ]
      num-prompts: [ 300 ]
      random-input-output-len: [ [70000, 1500] ]
    test_05:
      dataset-name: random
      max-concurrency: [ 1, 4, 8, 16, 32, 64, 128 ]
      num-prompts: [ 1000 ]
      random-input-output-len: [ [ 128, 128 ], [ 512, 256 ], [ 1024, 512 ],[ 2048, 1024 ],[ 4096, 2048 ],[ 8192, 1024 ]]
  temperature: 0.7
  seed: 123
  ready-check-timeout-sec: 30
models:
  inspur_MetaX_C550:
  - name: "MiniMax-M2.5-W8A8"
    served-model-name: "minimax-m2.5"
    model_path: "/data/data_shared/MiniMax-M2.5-W8A8"
  - name: "Kimi-K2.5_int4_2"
    served-model-name: "kimi-k2.5"
    model_path: "/data2/data_shared/Kimi-K2.5_int4_2"
  - name: "GLM-5-W8A8"
    served-model-name: "glm-5"
    model_path: "/var_docker/data_shared/GLM-5-W8A8"
  inspur_P800:
    - name: "MiniMax-M2.5-int8"
      served-model-name: "/work/models/ssd4/models/MiniMax-M2.5-int8"
      model_path: "/work/models/ssd4/models/MiniMax-M2.5-int8"
  PPU810:
    - name: "GLM-5.1-W4A8"
      served-model-name: "glm-5.1"
      model_path: "/mnt/data/GLM-5.1-W4A8"

# SGLang 版本
sglang_version: "0.5.9"